-- SQL Schema Setup for Jeshurun Builders & Developers
-- Run these queries in the Supabase Dashboard SQL Editor (https://supabase.com)

-- 1. Create Gallery Table
CREATE TABLE IF NOT EXISTS public.gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category text NOT NULL,
    img_url text NOT NULL,
    alt text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Team Table
CREATE TABLE IF NOT EXISTS public.team (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    role text NOT NULL,
    img_url text NOT NULL,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Brochure Slides Table
CREATE TABLE IF NOT EXISTS public.brochure_slides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    type text NOT NULL,
    img_url text,
    specs jsonb,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Leads Table
CREATE TABLE IF NOT EXISTS public.leads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Disable Row Level Security (RLS) on all tables so client-side SPA (using the anon key) can perform CRUD
ALTER TABLE public.gallery DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.team DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.brochure_slides DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads DISABLE ROW LEVEL SECURITY;
